/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramasSlugRouteImport } from './routes/programas.$slug'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AppsSlugPreviewRouteImport } from './routes/apps.$slug.preview'
import { Route as AuthenticatedAppProgramasRouteImport } from './routes/_authenticated/app.programas'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppCatalogoRouteImport } from './routes/_authenticated/app.catalogo'
import { Route as AdminAdminUsuariosRouteImport } from './routes/_admin/admin.usuarios'
import { Route as AdminAdminPlanosRouteImport } from './routes/_admin/admin.planos'
import { Route as AdminAdminNovidadesRouteImport } from './routes/_admin/admin.novidades'
import { Route as AdminAdminModulosRouteImport } from './routes/_admin/admin.modulos'
import { Route as AdminAdminFinanceiroRouteImport } from './routes/_admin/admin.financeiro'
import { Route as AdminAdminClientesIndexRouteImport } from './routes/_admin/admin.clientes.index'
import { Route as AuthenticatedAppProgramasSlugRouteImport } from './routes/_authenticated/app.programas.$slug'
import { Route as AuthenticatedAppConfiguracoesFiliaisRouteImport } from './routes/_authenticated/app.configuracoes.filiais'
import { Route as AdminAdminClientesIdRouteImport } from './routes/_admin/admin.clientes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasSlugRoute = ProgramasSlugRouteImport.update({
  id: '/programas/$slug',
  path: '/programas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AppsSlugPreviewRoute = AppsSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppsSlugRoute,
} as any)
const AuthenticatedAppProgramasRoute =
  AuthenticatedAppProgramasRouteImport.update({
    id: '/programas',
    path: '/programas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCatalogoRoute =
  AuthenticatedAppCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AdminAdminUsuariosRoute = AdminAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlanosRoute = AdminAdminPlanosRouteImport.update({
  id: '/admin/planos',
  path: '/admin/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNovidadesRoute = AdminAdminNovidadesRouteImport.update({
  id: '/admin/novidades',
  path: '/admin/novidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminModulosRoute = AdminAdminModulosRouteImport.update({
  id: '/admin/modulos',
  path: '/admin/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFinanceiroRoute = AdminAdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminClientesIndexRoute = AdminAdminClientesIndexRouteImport.update({
  id: '/admin/clientes/',
  path: '/admin/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAppProgramasSlugRoute =
  AuthenticatedAppProgramasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAppProgramasRoute,
  } as any)
const AuthenticatedAppConfiguracoesFiliaisRoute =
  AuthenticatedAppConfiguracoesFiliaisRouteImport.update({
    id: '/filiais',
    path: '/filiais',
    getParentRoute: () => AuthenticatedAppConfiguracoesRoute,
  } as any)
const AdminAdminClientesIdRoute = AdminAdminClientesIdRouteImport.update({
  id: '/admin/clientes/$id',
  path: '/admin/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/apps/$slug': typeof AppsSlugRouteWithChildren
  '/programas/$slug': typeof ProgramasSlugRoute
  '/admin/financeiro': typeof AdminAdminFinanceiroRoute
  '/admin/modulos': typeof AdminAdminModulosRoute
  '/admin/novidades': typeof AdminAdminNovidadesRoute
  '/admin/planos': typeof AdminAdminPlanosRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/app/catalogo': typeof AuthenticatedAppCatalogoRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRouteWithChildren
  '/app/programas': typeof AuthenticatedAppProgramasRouteWithChildren
  '/apps/$slug/preview': typeof AppsSlugPreviewRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/clientes/$id': typeof AdminAdminClientesIdRoute
  '/app/configuracoes/filiais': typeof AuthenticatedAppConfiguracoesFiliaisRoute
  '/app/programas/$slug': typeof AuthenticatedAppProgramasSlugRoute
  '/admin/clientes/': typeof AdminAdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/apps/$slug': typeof AppsSlugRouteWithChildren
  '/programas/$slug': typeof ProgramasSlugRoute
  '/admin/financeiro': typeof AdminAdminFinanceiroRoute
  '/admin/modulos': typeof AdminAdminModulosRoute
  '/admin/novidades': typeof AdminAdminNovidadesRoute
  '/admin/planos': typeof AdminAdminPlanosRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/app/catalogo': typeof AuthenticatedAppCatalogoRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRouteWithChildren
  '/app/programas': typeof AuthenticatedAppProgramasRouteWithChildren
  '/apps/$slug/preview': typeof AppsSlugPreviewRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/clientes/$id': typeof AdminAdminClientesIdRoute
  '/app/configuracoes/filiais': typeof AuthenticatedAppConfiguracoesFiliaisRoute
  '/app/programas/$slug': typeof AuthenticatedAppProgramasSlugRoute
  '/admin/clientes': typeof AdminAdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/apps/$slug': typeof AppsSlugRouteWithChildren
  '/programas/$slug': typeof ProgramasSlugRoute
  '/_admin/admin/financeiro': typeof AdminAdminFinanceiroRoute
  '/_admin/admin/modulos': typeof AdminAdminModulosRoute
  '/_admin/admin/novidades': typeof AdminAdminNovidadesRoute
  '/_admin/admin/planos': typeof AdminAdminPlanosRoute
  '/_admin/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/_authenticated/app/catalogo': typeof AuthenticatedAppCatalogoRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRouteWithChildren
  '/_authenticated/app/programas': typeof AuthenticatedAppProgramasRouteWithChildren
  '/apps/$slug/preview': typeof AppsSlugPreviewRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/clientes/$id': typeof AdminAdminClientesIdRoute
  '/_authenticated/app/configuracoes/filiais': typeof AuthenticatedAppConfiguracoesFiliaisRoute
  '/_authenticated/app/programas/$slug': typeof AuthenticatedAppProgramasSlugRoute
  '/_admin/admin/clientes/': typeof AdminAdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app'
    | '/apps/$slug'
    | '/programas/$slug'
    | '/admin/financeiro'
    | '/admin/modulos'
    | '/admin/novidades'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/app/catalogo'
    | '/app/configuracoes'
    | '/app/programas'
    | '/apps/$slug/preview'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/app/configuracoes/filiais'
    | '/app/programas/$slug'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app'
    | '/apps/$slug'
    | '/programas/$slug'
    | '/admin/financeiro'
    | '/admin/modulos'
    | '/admin/novidades'
    | '/admin/planos'
    | '/admin/usuarios'
    | '/app/catalogo'
    | '/app/configuracoes'
    | '/app/programas'
    | '/apps/$slug/preview'
    | '/admin'
    | '/admin/clientes/$id'
    | '/app/configuracoes/filiais'
    | '/app/programas/$slug'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/app'
    | '/apps/$slug'
    | '/programas/$slug'
    | '/_admin/admin/financeiro'
    | '/_admin/admin/modulos'
    | '/_admin/admin/novidades'
    | '/_admin/admin/planos'
    | '/_admin/admin/usuarios'
    | '/_authenticated/app/catalogo'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/programas'
    | '/apps/$slug/preview'
    | '/_admin/admin/'
    | '/_admin/admin/clientes/$id'
    | '/_authenticated/app/configuracoes/filiais'
    | '/_authenticated/app/programas/$slug'
    | '/_admin/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AppsSlugRoute: typeof AppsSlugRouteWithChildren
  ProgramasSlugRoute: typeof ProgramasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/$slug': {
      id: '/programas/$slug'
      path: '/programas/$slug'
      fullPath: '/programas/$slug'
      preLoaderRoute: typeof ProgramasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apps/$slug/preview': {
      id: '/apps/$slug/preview'
      path: '/preview'
      fullPath: '/apps/$slug/preview'
      preLoaderRoute: typeof AppsSlugPreviewRouteImport
      parentRoute: typeof AppsSlugRoute
    }
    '/_authenticated/app/programas': {
      id: '/_authenticated/app/programas'
      path: '/programas'
      fullPath: '/app/programas'
      preLoaderRoute: typeof AuthenticatedAppProgramasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/catalogo': {
      id: '/_authenticated/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AuthenticatedAppCatalogoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_admin/admin/usuarios': {
      id: '/_admin/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminAdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/planos': {
      id: '/_admin/admin/planos'
      path: '/admin/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminAdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/novidades': {
      id: '/_admin/admin/novidades'
      path: '/admin/novidades'
      fullPath: '/admin/novidades'
      preLoaderRoute: typeof AdminAdminNovidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/modulos': {
      id: '/_admin/admin/modulos'
      path: '/admin/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminAdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/financeiro': {
      id: '/_admin/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminAdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/clientes/': {
      id: '/_admin/admin/clientes/'
      path: '/admin/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminAdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/app/programas/$slug': {
      id: '/_authenticated/app/programas/$slug'
      path: '/$slug'
      fullPath: '/app/programas/$slug'
      preLoaderRoute: typeof AuthenticatedAppProgramasSlugRouteImport
      parentRoute: typeof AuthenticatedAppProgramasRoute
    }
    '/_authenticated/app/configuracoes/filiais': {
      id: '/_authenticated/app/configuracoes/filiais'
      path: '/filiais'
      fullPath: '/app/configuracoes/filiais'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesFiliaisRouteImport
      parentRoute: typeof AuthenticatedAppConfiguracoesRoute
    }
    '/_admin/admin/clientes/$id': {
      id: '/_admin/admin/clientes/$id'
      path: '/admin/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminAdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminFinanceiroRoute: typeof AdminAdminFinanceiroRoute
  AdminAdminModulosRoute: typeof AdminAdminModulosRoute
  AdminAdminNovidadesRoute: typeof AdminAdminNovidadesRoute
  AdminAdminPlanosRoute: typeof AdminAdminPlanosRoute
  AdminAdminUsuariosRoute: typeof AdminAdminUsuariosRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminClientesIdRoute: typeof AdminAdminClientesIdRoute
  AdminAdminClientesIndexRoute: typeof AdminAdminClientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminFinanceiroRoute: AdminAdminFinanceiroRoute,
  AdminAdminModulosRoute: AdminAdminModulosRoute,
  AdminAdminNovidadesRoute: AdminAdminNovidadesRoute,
  AdminAdminPlanosRoute: AdminAdminPlanosRoute,
  AdminAdminUsuariosRoute: AdminAdminUsuariosRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminClientesIdRoute: AdminAdminClientesIdRoute,
  AdminAdminClientesIndexRoute: AdminAdminClientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedAppConfiguracoesRouteChildren {
  AuthenticatedAppConfiguracoesFiliaisRoute: typeof AuthenticatedAppConfiguracoesFiliaisRoute
}

const AuthenticatedAppConfiguracoesRouteChildren: AuthenticatedAppConfiguracoesRouteChildren =
  {
    AuthenticatedAppConfiguracoesFiliaisRoute:
      AuthenticatedAppConfiguracoesFiliaisRoute,
  }

const AuthenticatedAppConfiguracoesRouteWithChildren =
  AuthenticatedAppConfiguracoesRoute._addFileChildren(
    AuthenticatedAppConfiguracoesRouteChildren,
  )

interface AuthenticatedAppProgramasRouteChildren {
  AuthenticatedAppProgramasSlugRoute: typeof AuthenticatedAppProgramasSlugRoute
}

const AuthenticatedAppProgramasRouteChildren: AuthenticatedAppProgramasRouteChildren =
  {
    AuthenticatedAppProgramasSlugRoute: AuthenticatedAppProgramasSlugRoute,
  }

const AuthenticatedAppProgramasRouteWithChildren =
  AuthenticatedAppProgramasRoute._addFileChildren(
    AuthenticatedAppProgramasRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCatalogoRoute: typeof AuthenticatedAppCatalogoRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRouteWithChildren
  AuthenticatedAppProgramasRoute: typeof AuthenticatedAppProgramasRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCatalogoRoute: AuthenticatedAppCatalogoRoute,
  AuthenticatedAppConfiguracoesRoute:
    AuthenticatedAppConfiguracoesRouteWithChildren,
  AuthenticatedAppProgramasRoute: AuthenticatedAppProgramasRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AppsSlugRouteChildren {
  AppsSlugPreviewRoute: typeof AppsSlugPreviewRoute
}

const AppsSlugRouteChildren: AppsSlugRouteChildren = {
  AppsSlugPreviewRoute: AppsSlugPreviewRoute,
}

const AppsSlugRouteWithChildren = AppsSlugRoute._addFileChildren(
  AppsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AppsSlugRoute: AppsSlugRouteWithChildren,
  ProgramasSlugRoute: ProgramasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
